name: haunt
description: Haunt Flame Game

dependencies:
  flutter:
    sdk: flutter
  box2d:

  flame:
      path: ../flame

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/ninja.png
    - assets/images/layers/layer_01.png
    - assets/images/layers/layer_02.png
    - assets/images/layers/layer_03.png
    - assets/images/layers/layer_04.png
    - assets/images/layers/layer_05.png
    - assets/images/layers/layer_06.png
    - assets/images/layers/layer_07.png
